---
- name: Check if ceph is already bootstrapped
  stat:
    path: /etc/ceph/ceph.conf
  register: ceph_bootstrapped

- name: Pre-pull Ceph container image
  command: podman pull quay.io/ceph/ceph:v19
  register: pull_result
  until: pull_result.rc == 0
  retries: 3
  delay: 10

- name: Bootstrap Ceph cluster on first MON
  shell: |
    cephadm bootstrap \
      --mon-ip {{ ansible_host }} \
      --cluster-network 192.168.56.0/24 \
      --initial-dashboard-user admin \
      --initial-dashboard-password admin \
      --skip-monitoring-stack \
      --skip-pull
  when:
    - not ceph_bootstrapped.stat.exists
    - inventory_hostname == groups['ceph_mons'][0]

- name: Get ceph public key
  slurp:
    src: /etc/ceph/ceph.pub
  register: ceph_pub_key
  when: inventory_hostname == groups['ceph_mons'][0]

- name: Distribute ceph public key to all MON nodes
  authorized_key:
    user: root
    key: "{{ hostvars[groups['ceph_mons'][0]].ceph_pub_key.content | b64decode }}"
    state: present
  when: hostvars[groups['ceph_mons'][0]].ceph_pub_key is defined

- name: Add ceph MON hosts to known_hosts on first MON
  shell: ssh-keyscan {{ hostvars[item].ansible_host }} >> /root/.ssh/known_hosts
  loop: "{{ groups['ceph_mons'] }}"
  when: inventory_hostname == groups['ceph_mons'][0]

- name: Add ALL MONs to cluster
  shell: ceph orch host add {{ item }} {{ hostvars[item].ansible_host }}
  loop: "{{ groups['ceph_mons'] }}"
  when: inventory_hostname == groups['ceph_mons'][0]
  ignore_errors: yes

- name: Wait for all hosts to be registered
  shell: ceph orch host ls | grep -c "wacloud-node"
  register: host_count
  until: host_count.stdout | int >= groups['ceph_mons'] | length
  retries: 10
  delay: 10
  when: inventory_hostname == groups['ceph_mons'][0]

- name: Deploy MGR
  shell: ceph orch apply mgr --placement="{{ groups['ceph_mgrs'][0] }}"
  when: inventory_hostname == groups['ceph_mons'][0]
